# Generated by Django 3.0.5 on 2024-06-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0002_porcentajechecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorInfo',
            fields=[
                ('evaluator_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('technological_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('personality_description', models.CharField(blank=True, max_length=255, null=True)),
                ('goals', models.CharField(blank=True, max_length=255, null=True)),
                ('habits', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
