# Generated by Django 3.0.5 on 2024-06-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0003_evaluatorinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, default='novato', max_length=10, null=True),
        ),
    ]
