# Generated by Django 3.0.5 on 2024-09-02 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0004_auto_20240612_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('description', models.CharField(default='N/A', max_length=500)),
                ('test_type', models.CharField(blank=True, choices=[('Movil', 'Movil'), ('Web', 'Web'), ('Tablet', 'Tablet')], max_length=6)),
                ('heuristics', models.CharField(blank=True, choices=[('Con heuristicas', 'Con heuristicas'), ('Sin heuristicas', 'Sin heuristicas')], max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('code', models.CharField(blank=True, default='e80134c2-f', max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatorAccess',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('acceso_bloqueado', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatorResponses',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_type', models.CharField(blank=True, choices=[('Calificacion', 'Calificación'), ('Legibilidad', 'Legibilidad'), ('Coherencia', 'Coherencia')], max_length=12)),
                ('response_value', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MovilHeuristics',
            fields=[
                ('HM', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MovilSubprinciples',
            fields=[
                ('HMS', models.AutoField(primary_key=True, serialize=False)),
                ('subtitle', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('example', models.TextField(default='')),
                ('HM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplications.MovilHeuristics')),
            ],
        ),
        migrations.RenameField(
            model_name='designquestionnaires',
            old_name='id',
            new_name='questionnaire_id',
        ),
        migrations.RemoveField(
            model_name='designquestionnaires',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='designquestionnaires',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='designquestionnaires',
            name='question',
        ),
        migrations.AddField(
            model_name='designquestionnaires',
            name='description',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='designquestionnaires',
            name='response_type',
            field=models.CharField(blank=True, choices=[('Calificacion', 'Calificación'), ('Legibilidad', 'Legibilidad'), ('Coherencia', 'Coherencia')], max_length=12),
        ),
        migrations.AddField(
            model_name='designquestionnaires',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='designquestionnaires',
            name='url_frame',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, choices=[('Novato', 'Novato'), ('Experto', 'Experto')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.TextField(choices=[('Administrador', 'Administrador'), ('Propietario', 'Propietario'), ('Evaluador', 'Evaluador')]),
        ),
        migrations.DeleteModel(
            name='DesignOwner',
        ),
        migrations.AddField(
            model_name='evaluatorresponses',
            name='evaluator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplications.User'),
        ),
        migrations.AddField(
            model_name='evaluatorresponses',
            name='questionnaire_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplications.DesignQuestionnaires'),
        ),
        migrations.AddField(
            model_name='evaluatorresponses',
            name='test_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplications.DesignTest'),
        ),
        migrations.AddField(
            model_name='evaluatoraccess',
            name='evaluator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplications.User'),
        ),
        migrations.AddField(
            model_name='evaluatoraccess',
            name='test_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplications.DesignTest'),
        ),
        migrations.AddField(
            model_name='designtest',
            name='user_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplications.User'),
        ),
        migrations.AddField(
            model_name='designquestionnaires',
            name='designtest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designtests', to='aplications.DesignTest'),
        ),
    ]
