# Generated by Django 3.0.5 on 2024-09-02 21:24

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0005_auto_20240902_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designtest',
            name='heuristics',
        ),
        migrations.RemoveField(
            model_name='designtest',
            name='user_id',
        ),
        migrations.AddField(
            model_name='designtest',
            name='has_heuristics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designtest',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplications.User'),
        ),
        migrations.AlterField(
            model_name='designtest',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='designtest',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.CreateModel(
            name='DesignQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url_frame', models.URLField(max_length=500)),
                ('is_heuristic', models.BooleanField(default=False)),
                ('response_type', models.CharField(blank=True, max_length=12, null=True)),
                ('heuristics', jsonfield.fields.JSONField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplications.DesignTest')),
            ],
        ),
        migrations.AlterField(
            model_name='evaluatorresponses',
            name='questionnaire_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplications.DesignQuestion'),
        ),
        migrations.DeleteModel(
            name='DesignQuestionnaires',
        ),
    ]
