# Generated by Django 3.0.5 on 2024-09-02 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0006_auto_20240902_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designtest',
            name='user',
        ),
        migrations.AddField(
            model_name='designtest',
            name='user_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplications.User'),
        ),
    ]
