# Generated by Django 3.0.5 on 2024-09-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0007_auto_20240902_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designquestion',
            name='is_heuristic',
        ),
        migrations.AlterField(
            model_name='designquestion',
            name='response_type',
            field=models.CharField(blank=True, choices=[('Calificacion', 'Calificación'), ('Legibilidad', 'Legibilidad'), ('Coherencia', 'Coherencia')], max_length=12, null=True),
        ),
    ]
