# Generated by Django 3.0.5 on 2024-09-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0008_auto_20240902_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heuristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subprinciple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('example', models.TextField()),
                ('heuristic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprinciples', to='aplications.Heuristic')),
            ],
        ),
        migrations.RemoveField(
            model_name='movilsubprinciples',
            name='HM',
        ),
        migrations.DeleteModel(
            name='MovilHeuristics',
        ),
        migrations.DeleteModel(
            name='MovilSubprinciples',
        ),
    ]
