# Generated by Django 3.0.5 on 2024-09-05 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0011_auto_20240903_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluatoraccess',
            old_name='hidden',
            new_name='is_hidden',
        ),
        migrations.AddField(
            model_name='evaluatoraccess',
            name='accessed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
