# Generated by Django 3.0.5 on 2024-09-05 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0013_auto_20240904_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorHeuristicResponse',
            fields=[
                ('heuristic_response_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatorStandardResponse',
            fields=[
                ('standard_response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_type', models.CharField(choices=[('Calificacion', 'Calificación'), ('Legibilidad', 'Legibilidad'), ('Coherencia', 'Coherencia')], max_length=12)),
                ('response_value', models.IntegerField()),
                ('comment', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Propietario', 'Propietario'), ('Evaluador', 'Evaluador')], max_length=15),
        ),
        migrations.DeleteModel(
            name='EvaluatorResponses',
        ),
        migrations.AddField(
            model_name='evaluatorstandardresponse',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplications.User'),
        ),
        migrations.AddField(
            model_name='evaluatorstandardresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplications.DesignQuestion'),
        ),
        migrations.AddField(
            model_name='evaluatorstandardresponse',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplications.DesignTest'),
        ),
        migrations.AddField(
            model_name='evaluatorheuristicresponse',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplications.User'),
        ),
        migrations.AddField(
            model_name='evaluatorheuristicresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplications.DesignQuestion'),
        ),
        migrations.AddField(
            model_name='evaluatorheuristicresponse',
            name='subprinciple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplications.Subprinciple'),
        ),
        migrations.AddField(
            model_name='evaluatorheuristicresponse',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplications.DesignTest'),
        ),
    ]
