# Generated by Django 3.0.5 on 2024-09-05 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0014_auto_20240905_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatorheuristicresponse',
            name='evaluator_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplications.EvaluatorAccess'),
        ),
        migrations.AddField(
            model_name='evaluatorheuristicresponse',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluatorstandardresponse',
            name='evaluator_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplications.EvaluatorAccess'),
        ),
        migrations.AddField(
            model_name='evaluatorstandardresponse',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
