# Generated by Django 3.0.5 on 2024-09-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0015_auto_20240905_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatoraccess',
            name='acceso_bloqueado',
            field=models.BooleanField(default=True),
        ),
    ]
