# Generated by Django 3.0.5 on 2024-09-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0019_auto_20240915_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designtest',
            old_name='user',
            new_name='user_id',
        ),
    ]
