# Generated by Django 3.0.5 on 2024-09-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0021_auto_20240915_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designtest',
            old_name='user_id',
            new_name='user',
        ),
    ]
