# Generated by Django 3.0.5 on 2024-09-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0022_auto_20240915_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rol',
            new_name='role',
        ),
    ]
