# Generated by Django 3.0.5 on 2024-09-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0023_auto_20240915_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='rol',
        ),
    ]
