# Generated by Django 3.0.5 on 2024-09-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0024_auto_20240915_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtest',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
