# Generated by Django 3.0.5 on 2024-09-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0025_auto_20240917_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='designtest',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
